import { eq, desc, sql } from "drizzle-orm";
import { db } from "./db";
import {
  repositories, users, downloadLogs, feedbackRequests,
  type InsertRepository, type Repository,
  type InsertFeedbackRequest, type UpsertUser, type InsertDownloadLog,
} from "@shared/schema";
import archiver from "archiver";
import { PassThrough } from "stream";

export class Storage {
  // ── Repositories ──
  async createRepository(data: InsertRepository): Promise<Repository> {
    const [repo] = await db.insert(repositories).values(data).returning();
    return repo;
  }

  async getRepository(id: number): Promise<Repository | undefined> {
    return db.query.repositories.findFirst({ where: eq(repositories.id, id) });
  }

  async listRepositories(): Promise<Repository[]> {
    return db.select().from(repositories).orderBy(desc(repositories.createdAt));
  }

  async updateRepositoryStatus(id: number, status: string, progress: number) {
    await db.update(repositories).set({ status, progress }).where(eq(repositories.id, id));
  }

  // ── Users ──
  async upsertUser(data: UpsertUser) {
    const [user] = await db
      .insert(users)
      .values({ ...data, updatedAt: new Date() })
      .onConflictDoUpdate({ target: users.id, set: { updatedAt: new Date() } })
      .returning();
    return user;
  }

  async getUser(id: string) {
    return db.query.users.findFirst({ where: eq(users.id, id) });
  }

  // ── Download Logs ──
  async logDownload(data: InsertDownloadLog) {
    await db.insert(downloadLogs).values(data);
  }

  // ── Feedback ──
  async createFeedback(data: InsertFeedbackRequest) {
    const [fb] = await db.insert(feedbackRequests).values(data).returning();
    return fb;
  }

  async listFeedback() {
    return db.select().from(feedbackRequests).orderBy(desc(feedbackRequests.createdAt));
  }

  // ── Analytics ──
  async getAnalytics() {
    const totalDownloads = await db.select({ count: sql<number>`count(*)` }).from(downloadLogs);
    const uniqueUsers = await db.select({ count: sql<number>`count(distinct ${downloadLogs.userId})` }).from(downloadLogs);
    const topUseCases = await db
      .select({ useCase: downloadLogs.useCase, count: sql<number>`count(*)` })
      .from(downloadLogs)
      .groupBy(downloadLogs.useCase)
      .orderBy(desc(sql`count(*)`))
      .limit(10);
    const topLanguages = await db
      .select({ language: downloadLogs.language, count: sql<number>`count(*)` })
      .from(downloadLogs)
      .groupBy(downloadLogs.language)
      .orderBy(desc(sql`count(*)`))
      .limit(10);
    const feedbackCount = await db.select({ count: sql<number>`count(*)` }).from(feedbackRequests);

    return {
      totalDownloads: totalDownloads[0]?.count ?? 0,
      uniqueUsers: uniqueUsers[0]?.count ?? 0,
      topUseCases,
      topLanguages,
      feedbackCount: feedbackCount[0]?.count ?? 0,
    };
  }

  // ── ZIP Generation ──
  async generateRepositoryZip(id: number): Promise<Buffer> {
    const repo = await this.getRepository(id);
    const repoName = repo?.name ?? `repository-${id}`;

    const archive = archiver("zip", { zlib: { level: 9 } });
    const chunks: Uint8Array[] = [];
    const passthrough = new PassThrough();
    passthrough.on("data", (chunk) => chunks.push(chunk));
    archive.on("error", (err) => { throw err; });
    archive.pipe(passthrough);

    archive.append(`# ${repoName}\n\nGenerated by Cloud Demo Generator v3\n`, { name: "README.md" });
    archive.append(`console.log("Hello from ${repoName}");`, { name: "src/index.js" });
    archive.append(JSON.stringify({ name: repoName, version: "1.0.0" }, null, 2), { name: "package.json" });

    await archive.finalize();
    return Buffer.concat(chunks);
  }
}
